apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
      manifests:
          - ./infra/k8s/*
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
  artifacts:
    - image: userbogdan/auth
      docker:
        dockerfile: services/auth/Dockerfile
      # sync:
      #   manual:
      #     - src: 'services/auth/**/*.go'
      #       dest: .
    - image: userbogdan/tickets
      docker:
        dockerfile: services/tickets/Dockerfile
      # sync:
      #   manual:
      #     - src: 'services/tickets/**/*.go'
      #       dest: .